package com.cj.MyCompliar;

public enum Tt{
	FLOAT,INT,ID,MULOP,ADDOP,SELFADD,SELFDEC,LEFTBRA,RIGHTBRA,ASSIGN,BOOLOP,BOOLOP2,BOOLOP3,
	LEA,POINTTO,ARGTYPE,
	LEFTBIGBRA,RIGHTBIGBRA,COMMA,TRUE,FALSE,LEFTQBRA,RIGHTQBRA,
	EOF,
	IF,THEN,ELSE,TYPE,RETURN,WHILE,DO,WRITE,READ,VOID,
	ENDF,  //以endf为终结符分割
	_EXP,EXP,TEM,FAC,CALL,STEM,STEMS,ARGS,ARGSGIRD,BLOCK,
	BOOLEXP,BOOLEXP2,BOOLEXP3,DECLARE,ARGDECLARE,ARGDECLARES,DECLARES,PROCESS,PROCESSES,PROGRAM,_PROGRAM;
}
